animetacchi/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
from django.conf import settings

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'animetacchi.views.home', name='home'),
    url(r'^about/$', 'animetacchi.views.about', name='about'),
    url(r'^services/$', 'animetacchi.views.services', name='services'),
    
    # account
    url(r'^logout/$', 'animetacchi.views.logout', name='logout'),
    url(r'^signin/$', 'animetacchi.views.signin', name='signin'),
    url(r'^signup/$', 'animetacchi.views.signup', name='signup'),
    url(r'^confirm/(?P<activation_key>[a-zA-Z\-\_0-9\: ]+)/$', 'animetacchi.views.register_confirm', name='confirm'),
    url(r'^check-email/$', 'animetacchi.views.check_email', name='check_email'),
    
    # chart
    url(r'^chart/(?P<season>[a-zA-Z\-\_0-9]+)/$', 'animetacchi.views.anime_chart', name='anime_chart'),
    
    # anime
    url(r'^anime/$', 'animetacchi.views.anime', name='anime'),    
    url(r'^anime/(?P<slug>[a-zA-Z\-\_0-9\: ]+)/$', 'animetacchi.views.anime_details', name='anime_details'),
    url(r'^anime/(?P<slug>[a-zA-Z\-\_0-9\: ]+)/reviews/$', 'animetacchi.views.anime_reviews', name='anime_reviews'),
    url(r'^anime/(?P<slug>[a-zA-Z\-\_0-9\: ]+)/reviews/add/$', 'animetacchi.views.anime_reviews_add', name='anime_reviews_add'),
    url(r'^anime/(?P<slug>[a-zA-Z\-\_0-9\: ]+)/character/(?P<id>\d+)/$', 'animetacchi.views.anime_character', name='anime_character'),
    url(r'^anime/voice/(?P<id>\d+)/$', 'animetacchi.views.anime_voice', name='anime_voice'),
    
    url(r'^daikirai/$', 'animetacchi.views.daikirai', name='daikirai'),
    url(r'^daisuki/$', 'animetacchi.views.daisuki', name='daisuki'),
    url(r'^watchlist/$', 'animetacchi.views.watchlist', name='watchlist'),
    url(r'^readinglist/$', 'animetacchi.views.readinglist', name='readinglist'),
    
    
    
    # manga
    url(r'^manga/$', 'animetacchi.views.manga', name='manga'),
    url(r'^manga/(?P<slug>[a-zA-Z\-\_0-9\: ]+)/$', 'animetacchi.views.manga_details', name='manga_details'),    
    url(r'^manga/(?P<slug>[a-zA-Z\-\_0-9\: ]+)/reviews/$', 'animetacchi.views.manga_reviews', name='manga_reviews'),
    url(r'^manga/(?P<slug>[a-zA-Z\-\_0-9\: ]+)/reviews/add/$', 'animetacchi.views.manga_reviews_add', name='manga_reviews_add'),
    url(r'^manga/(?P<slug>[a-zA-Z\-\_0-9\: ]+)/character/(?P<id>\d+)/$', 'animetacchi.views.manga_character', name='manga_character'),
    
    # user
    url(r'^dashboard/(?P<username>[-\w.]+)/$', 'animetacchi.views.dashboard', name='dashboard'),
    url(r'^upload_pic/$', 'animetacchi.views.upload_pic', name='upload_pic'),
    url(r'^users/(?P<username>[-\w.]+)/$', 'animetacchi.views.users', name='users'),
    url(r'^users/(?P<username>[-\w.]+)/library/$', 'animetacchi.views.library', name='library'),    
    url(r'^users/(?P<username>[-\w.]+)/library/manga/$', 'animetacchi.views.library_manga', name='library_manga'),
    url(r'^forgot-password/$', 'animetacchi.views.forgot_password', name='forgot-password'),
    url(r'^password_reset/done/$', 'animetacchi.views.cust_password_reset_done'),
    url(r'^reset/(?P<uidb36>[-\w]+)/(?P<token>[-\w]+)/$', 'animetacchi.views.cust_password_reset_confirm'),
    url(r'^reset/done/$', 'animetacchi.views.cust_password_reset_complete'),


    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    #ratings
    url(r'^ratings/', include('ratings.urls')),
    url(r'^ratings/average/(?P<entity>[a-zA-Z\-\_0-9\: ]+)/(?P<id>[a-zA-Z\-\_0-9\: ]+)/', 'animetacchi.views.ratings_average', name='ratings_average'),
    
    #likes
    url(r'^likes/(?P<entity>[a-zA-Z\-\_0-9\: ]+)/', 'animetacchi.views.likes', name='likes'),
    url(r'^show_likes/(?P<entity>[a-zA-Z\-\_0-9\: ]+)/(?P<id>[a-zA-Z\-\_0-9\: ]+)/', 'animetacchi.views.show_likes', name='show_likes'),
    
    url(r'^sort_comment/$', 'animetacchi.views.sort_comment', name='sort_comment'),
    url(r'^sort_comment_manga/$', 'animetacchi.views.sort_comment_manga', name='sort_comment_manga'),
    
    url(r'^search_comment/$', 'animetacchi.views.search_comment', name='search_comment'),
    
    url(r'^request_edit/$', 'animetacchi.views.request_edit', name='request_edit'),

)
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
)

vote/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType

try:
    from django.contrib.contenttypes.fields import GenericForeignKey
except ImportError:
    from django.contrib.contenttypes.generic import GenericForeignKey

from .compat import AUTH_USER_MODEL

class VoteManger(models.Manager):
    def filter(self, *args, **kwargs):
        if 'content_object' in kwargs:
            content_object = kwargs.pop('content_object')
            content_type = ContentType.objects.get_for_model(content_object)
            kwargs.update({
                    'content_type':content_type,
                    'object_id':content_object.pk
                    })
        return super(VoteManger, self).filter(*args, **kwargs)
    
class Vote(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL)
    content_type = models.ForeignKey(ContentType, related_name='vote_content_type')
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()
    create_at = models.DateTimeField(auto_now_add=True)

    objects = VoteManger()
    
    class Meta:
        unique_together = ('user', 'content_type', 'object_id')

    @classmethod
    def votes_for(cls, model, instance=None):
        ct = ContentType.objects.get_for_model(model)
        kwargs = {
            "content_type": ct
        }
        if instance is not None:
            kwargs["object_id"] = instance.pk
            
        return cls.objects.filter(**kwargs)

templates/anime_character.html
{% extends 'anime_details.html' %}
{% load ratings_tags %}
{% block js %}
<script>
        
        
        function daikirai(character_id){
            
            $.ajax({
                type: "POST",
                cache: false,
                url: "{% url 'daikirai' %}",
                data: {
                    'username': "{{request.user.username}}",
                    'character_id': character_id,
                    'csrfmiddlewaretoken': '{{csrf_token}}'
                },
                success:function(response){
                    $('#daikirai').hide();
                    $('#daisuki').show();
                    $.notify("Added to your daikirailist", "danger");
                    setTimeout('RedirectUpdate()', 2000);
                }
            });
        }
		
		function daisuki(character_id){
            
            $.ajax({
                type: "POST",
                cache: false,
                url: "{% url 'daisuki' %}",
                data: {
                    'username': "{{request.user.username}}",
                    'character_id': character_id,
                    'csrfmiddlewaretoken': '{{csrf_token}}'
                },
                success:function(response){
                    $('#daisuki').hide();
                    $('#daikirai').show();
                    $.notify("Added to your daisukilist", "info");
                    setTimeout('RedirectUpdate()', 2000);
                }
            });
        }
</script>

{% endblock %}
{% block body%}
    <!--Main Slider-->
           


    <div class="sidebar-page" style="padding:130px 0px 134px;">
        <div class="auto-container">
            <div class="row clearfix" style="margin-top:-20px;">
                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12" id="formAnimes">
                    <div class="row">
                        <div class="col-md-12">
                            <section class="panel">
                                <div class="panel-body">
                                    <div class="col-md-4 col-sm-6 col-xs-12" style="margin:-5px 0 0 -20px;">
                                        <!--Image-->
                                        <figure class="image">
                                            <a href="#" class="lightbox-image"
                                               title="{{character.name}}"><img src="{{ MEDIA_URL }}{{character.picture}}" alt="" width="215" height="311" style="border-radius:5px;"></a>
                                        </figure>
                                    </div>
									{% block character_detail %} 
                                    <div class="col-md-8 col-sm-6 col-xs-12">
                                        <!--Content-Column-->
                                        <div class="cont-column">
                                            <div class="inner-box">
                                                <h3 class="anime-title"><a href="#">{{character.name}}</a></h3>
												
                                                <div class="item-cats subtitle">from <a href="{% url 'anime_details' character.anime.slug %}" >{{character.anime}}</a>
                                                </div>
                                                <div class="description anime-desc" >
                                                    {{character.synopsys}}
                                                </div>                                                
                                                
											{% if request.user.is_authenticated %}
													{% get_rating_form for character as rating_form %}
													<form id="rate-form">
														{% csrf_token %}
														{{ rating_form }}
														
													</form>
													<div id="ratings-average">
														{% get_rating_score for character as score %}
														{% if score %}
															Average ratings: {{ score.average|floatformat }}<br>
															Number of votes: {{ score.num_votes }}<br>
														{% else %}
															How sad: nobody voted {{ film }}<br>
														{% endif %}
													</div>
													
													<div class="btn-group">													
														<button {% if daisuki %} style="display:none;" {% endif %}  id="daisuki" class="btn btn-info" onclick="daisuki({{character.id}})" type="button">
															Add to Daisukilist </button>
													</div><!--btn-group-->
													
													<div id="daikirai" class="btn-group">													
														<button {% if daikirai %} style="display:none;" {% endif %} class="btn btn-danger" onclick="daikirai({{character.id}})" type="button">
															Add to Daikirailist </button>
													</div><!--btn-group-->
											{% endif %}
												
                                            </div>
                                        </div>
                                    </div>
                                    {% endblock %}                                
                                </div>
                            </section>
                        </div>
                    </div>                    
                </div>               
            </div>
        </div>
    </div>

{% block ratings %}
	<script type="text/javascript">
        $(document).ready(function() {
			$('#id_score').addClass('rating');
			$('#id_score').attr('type', 'hidden');
		});
		
		 $("#rate-form").click(function() {
                rate();
          });
          
          function rate(){
            
            $.ajax({
                type: "POST",
                cache: false,
                url: "{% url 'ratings_vote' %}",
                data: {
					'honeypot': $('#id_honeypot').val(),
					'security_hash': $('#id_security_hash').val(),
					'timestamp': $('#id_timestamp').val(),
					'key': $('#id_key').val(),
					'object_pk': $('#id_object_pk').val(),
					'content_type': $('#id_content_type').val(),
					'score': $('#id_score').val(),
                    'csrfmiddlewaretoken': '{{csrf_token}}'
                },
                success:function(response){
					$.get("{% url 'ratings_average' entity='character' id=character.id %}", function(data, status){
						
						$('#ratings-average').html(data)
					});
                    $.notify("Rated "+ status, "default");
                    setTimeout('RedirectUpdate()', 2000);
                }
            });
        }
	</script>
{% endblock %}    

{% endblock %}

templates/anime_chart.html
{% extends 'base_menu.html' %}

{% block css %}
    <link href="{{ MEDIA_URL }}css/bootstrap.css" rel="stylesheet">
	<link href="{{ MEDIA_URL }}css/freelancer.min.css" rel="stylesheet">
    <link href="{{ MEDIA_URL }}css/shop-homepage.css" rel="stylesheet">
    <link href="{{ MEDIA_URL }}css/nouislider.css" rel="stylesheet">
    <link href="{{ MEDIA_URL }}css/nouislider.pips.css" rel="stylesheet">
    <link href="{{ MEDIA_URL }}css/bootstrap-reset.css" rel="stylesheet">
    <style>
        .anime-title:after {
            content: '';
            position: absolute;
            left: 15px;
            bottom: 0px;
            width: 70px;
            height: 4px;
            background: #11c3f0;
        }
    </style>

{% endblock %}

{% block body%}

    <div class="sidebar-page">
    	<div class="auto-container">
    		<div class="row clearfix">
            	<!--Left Content-->
            	<!--<div class="col-xs-12"-->
                <!--Products Section
                    <section class="products-section">-->
						<div class="shop-filters category-filters">
                            <div class="clearfix">
                                <!--Filter Outer-->
                                <div class="col-lg-10 col-md-6 col-sm-6 col-xs-12 pull-left">
                                    <div class="tabs-box">
										<!-- Tab Buttons -->
										<div class="tab-buttons anim-3-all clearfix">
											<a href="{% url 'anime_chart' season='winter' %}" class="tab-btn {% if season == 'winter' %} active {% endif %}">Winter</a>
											<a href="{% url 'anime_chart' season='spring' %}" class="tab-btn {% if season == 'spring' %} active {% endif %}">Spring</a>
											<a href="{% url 'anime_chart' season='summer' %}" class="tab-btn {% if season == 'summer' %} active {% endif %}">Summer</a>
											<a href="{% url 'anime_chart' season='fall' %}" class="tab-btn {% if season == 'fall' %} active {% endif %}">Fall</a>
										</div>
									</div>
                                    <div class="chart-title">
                                        <h3>Chart</h3>
                                    </div>
                                </div> <!--end of filter outer-->
                            </div><!--end of clearfix-->
                        </div>
                        <div id="anime_data">
                            <div class="row clearfix chart">
								{% for i in anime_data.anime.all %}

                                <!--Column-->
                                <div class="product-item col-lg-4 col-md-6 col-sm-6 col-xs-6" style="margin-bottom: 75px;">
                                    <div class="inner-box tooltips" style="width:129;height:187px;" data-toggle="tooltip" data-placement="top"
                                    title="{{i.a_name}}">
                                        <div class="row">
											<div class="col-md-6 col-sm-6 col-xs-12" style="margin:15px 0 0 0px;">
												<!--Image-->
												<div class="thumbnail">
													<a href="{% url 'anime_details' slug=i.slug %}" class="lightbox-image"
													title="Awsome Title Here"><img src="{{ MEDIA_URL }}{{i.a_displaypic}}" alt="" width="215" height="311" style="border-radius:5px;"></a>
												</div>
											</div>
											<div class="col-md-6 col-sm-6 col-xs-12">
											<!--Content-Column-->
												<div class="cont-column">
													<div class="inner-box">
														<h5><a href="{% url 'anime_details' slug=i.slug %}">{{i.a_name}}</a></h5>
														<div class="item-cats subtitle">Aired from {{i.a_airedstart}} to {{i.a_airedend}}</div>
														<div class="description anime-desc" >{{i.a_synopsys|truncatechars:250}}</div>
													</div>
												</div>
											</div>
										</div><!--end of row-->
									</div>
                                </div>
                                {% empty %}
                                <div class="col-lg-6" style="margin-bottom: 335px;">
									<p><strong>Sorry no anime on this chart.</strong></p>
                                </div>
                                {% endfor %}



                            </div>



                        </div>

                    <!--</section>-->

                <!--</div--End Left Content-->




            </div>
        </div>

    </div>

{% endblock %}

templates/anime_reviews_add.html
{% extends 'base_menu.html' %}

{% block css %}

    <link href="{{ MEDIA_URL }}css/style2.css" rel="stylesheet">
    <link href="{{ MEDIA_URL }}css/bootstrap-reset.css" rel="stylesheet">

    <link href="{{ MEDIA_URL }}css/style-responsive.css" rel="stylesheet" />
    <link href="{{ MEDIA_URL }}css/anime-style.css" rel="stylesheet" />

{% endblock %}
{% block js %}

{% endblock %}

{% block body%}
    <!--Main Slider-->
    {% with anime_data as i %}
        <section class="page-title anime-cover" style="background-image: url({{ MEDIA_URL }}{{i.a_cover}});">
        </section>


    <div class="sidebar-page">
        <div class="auto-container">
            <div class="row clearfix" style="margin-top:-20px;">
                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 col-lg-offset-2 col-md-offset-2">
                    <section class="panel panel-default  post-comments">
                        <div class="panel-heading">
                            New Comments
                            
                        </div>
                        
                        <div class="media p15">
                            
							
                            <div class="comment">
                                
                                
                                <form method="POST">
                                    <div class="form-group">
										{% csrf_token %}
                                        <textarea class="form-control" rows="9" placeholder="Write something..." name="comment"></textarea>
                                    </div>
                                    <button type="submit" class="btn btn-primary">POST</button>
                                </form>

                                
                                <hr>
                        </div>
                        
                        
                        
                    </section>
                    
                </div>
            </div>
        </div>
    </div>

    {% endwith %}

{% endblock %}

templates/base_home.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Animetacchi</title>
<!-- Stylesheets -->
<link href="{{ MEDIA_URL }}css/bootstrap.css" rel="stylesheet">
<link href="{{ MEDIA_URL }}css/revolution-slider.css" rel="stylesheet">
<link href="{{ MEDIA_URL }}css/style.css" rel="stylesheet">
<link href="{{ MEDIA_URL }}css/freelancer.min.css" rel="stylesheet">
<!-- Responsive -->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<link href="{{ MEDIA_URL }}css/responsive.css" rel="stylesheet">

<script src="{{ MEDIA_URL }}signin/js/jquery.min.js"></script>
<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
<!--[if lt IE 9]><script src="{{ MEDIA_URL }}js/respond.js"></script><![endif]-->

    {% block css %}
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>

<body class="theme-orange">
<div class="page-wrapper">

    <!-- Preloader -->
    <div class="preloader"></div>

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" style="height: 44px;">
                    <span class="sr-only">Toggle navigation</span><i class="fa fa-bars" style="font-size: 20px;margin-top: 5px;"></i>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">Animetacchi</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                {% include 'base/navigation.html' %}
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <!-- Main Header / Sticky Header-->
    <header class="main-header sticky-header">
        
        <!-- Header Lower -->
        <div class="header-lower">
            	
                <!--Outer Box-->
                <div class="outer-box clearfix">
    
                    
                </div>
        </div><!-- Header Lower End-->
        
    </header><!--End Main Header -->


    {% block body %}
    {% endblock %}





</div>
<!--End pagewrapper-->

<!--Scroll to top-->
<div class="scroll-to-top"><span class="fa fa-arrow-up"></span></div>


<!--Search Popup-->
<div id="search-popup" class="search-popup">
	<div class="close-search theme-btn"><span class="flaticon-close7"></span></div>
	<div class="popup-inner">

    	<div class="search-form">
        	<form method="post" action="index.html">
            	<div class="form-group">
                	<fieldset>
                        <input type="search" class="form-control" name="search-input" value="" placeholder="Search Here" required >
                        <input type="submit" value="Search Now!" class="theme-btn">
                    </fieldset>
                </div>
            </form>

            <br>
            <h3>Recent Search Keywords</h3>
            <ul class="recent-searches">
                <li><a href="#">Business</a></li>
                <li><a href="#">Web Development</a></li>
                <li><a href="#">SEO</a></li>
                <li><a href="#">Logistics</a></li>
                <li><a href="#">Freedom</a></li>
            </ul>

        </div>

    </div>
</div>

<script src="{{ MEDIA_URL }}js/jquery.js"></script>
<script src="{{ MEDIA_URL }}js/bootstrap.min.js"></script>
<script src="{{ MEDIA_URL }}js/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="{{ MEDIA_URL }}js/revolution.min.js"></script>
<script src="{{ MEDIA_URL }}js/bxslider.js"></script>
<script src="{{ MEDIA_URL }}js/owl.js"></script>
<script src="{{ MEDIA_URL }}js/mixitup.js"></script>
<script src="{{ MEDIA_URL }}js/jquery.fancybox.pack.js"></script>
<script src="{{ MEDIA_URL }}js/owl.js"></script>
<script src="{{ MEDIA_URL }}js/wow.js"></script>
<script src="{{ MEDIA_URL }}js/script.js"></script>
<script src="{{ MEDIA_URL }}signin/js/app.v2.js"></script>
<script src="{{ MEDIA_URL }}signin/js/formValidation.min.js"></script>
<script src="{{ MEDIA_URL }}signin/js/bootstrap.min.js"></script>
<script src="{{ MEDIA_URL }}js/notify.min.js"></script>

</body>
</html>

templates/manga_character.html
{% extends 'anime_character.html' %}							
{% load ratings_tags %}
{% block js %}
<script>
        
        
        function daikirai(character_manga_id){
            
            $.ajax({
                type: "POST",
                cache: false,
                url: "{% url 'daikirai' %}",
                data: {
                    'username': "{{request.user.username}}",
                    'character_manga_id': character_manga_id,
                    'csrfmiddlewaretoken': '{{csrf_token}}'
                },
                success:function(response){
                    $('#daikirai').remove();
                }
            });
        }
		
		function daisuki(character_manga_id){
            
            $.ajax({
                type: "POST",
                cache: false,
                url: "{% url 'daisuki' %}",
                data: {
                    'username': "{{request.user.username}}",
                    'character_manga_id': character_manga_id,
                    'csrfmiddlewaretoken': '{{csrf_token}}'
                },
                success:function(response){
                    $('#daisuki').remove();
                }
            });
        }
</script>

{% endblock %}
	
								{% block character_detail %} 
                                    <div class="col-md-8 col-sm-6 col-xs-12">
                                        <!--Content-Column-->
                                        <div class="cont-column">
                                            <div class="inner-box">
                                                <h3 class="anime-title"><a href="#">{{character.name}}</a></h3>
												
                                                <div class="item-cats subtitle">from <a href="{% url 'manga_details' slug=character.manga.slug %}" >{{character.manga}}</a>
                                                </div>
                                                <div class="description anime-desc" >
                                                    {{character.synopsys}}
                                                </div>                                                
                                                
												{% if request.user.is_authenticated %}
												{% get_rating_form for character as rating_form %}
													<form id="rate-form">
														{% csrf_token %}
														{{ rating_form }}
														
													</form>
													<div id="ratings-average">
														{% get_rating_score for character as score %}
														{% if score %}
															Average ratings: {{ score.average|floatformat }}<br>
															Number of votes: {{ score.num_votes }}<br>
														{% else %}
															How sad: nobody voted {{ film }}<br>
														{% endif %}
													</div>
												
												<div class="btn-group">													
													<button {% if daisuki %} style="display:none;" {% endif %}  id="daisuki" class="btn btn-info" onclick="daisuki({{character.id}})" type="button">
															Add to Daisukilist </button>
													</div><!--btn-group-->
													
													<div id="daikirai" class="btn-group">													
														<button {% if daikirai %} style="display:none;" {% endif %} class="btn btn-danger" onclick="daikirai({{character.id}})" type="button">
															Add to Daikirailist </button>
													</div><!--btn-group-->
											{% endif %}
												
                                            </div>
                                        </div>
                                    </div>
                                    {% endblock %}
                                    
     {% block ratings %}
	<script type="text/javascript">
        $(document).ready(function() {
			$('#id_score').addClass('rating');
			$('#id_score').attr('type', 'hidden');
		});
		
		 $("#rate-form").click(function() {
                rate();
          });
          
          function rate(){
            
            $.ajax({
                type: "POST",
                cache: false,
                url: "{% url 'ratings_vote' %}",
                data: {
					'honeypot': $('#id_honeypot').val(),
					'security_hash': $('#id_security_hash').val(),
					'timestamp': $('#id_timestamp').val(),
					'key': $('#id_key').val(),
					'object_pk': $('#id_object_pk').val(),
					'content_type': $('#id_content_type').val(),
					'score': $('#id_score').val(),
                    'csrfmiddlewaretoken': '{{csrf_token}}'
                },
                success:function(response){
					$.get("{% url 'ratings_average' entity='character_manga' id=character.id %}", function(data, status){
						
						$('#ratings-average').html(data)
					});
                    $.notify("Rated "+ status, "default");
                    setTimeout('RedirectUpdate()', 2000);
                }
            });
        }
	</script>
                                    {% endblock %}

templates/manga_data.html
<div class="row clearfix">
    {% for i in manga_data %}

    <!--Column-->
    <article class="product-item col-lg-2 col-md-6 col-sm-12 col-xs-12">
        <div class="inner-box tooltips" style="width:129;height:187px;"
             data-toggle="tooltip" data-placement="top" title="{{i.name}}">
            <figure class="image" style="border-radius:5px;"><a href="#"><img
                    src="{{ MEDIA_URL }}{{i.displaypic}}" alt=""></a>

                <div class="product-content"
                     style="white-space: nowrap;text-overflow: ellipsis;overflow: hidden;">
                    <a href="#">{{i.name}}</a></div>
            </figure>
        </div>
    </article>
    {% endfor %}

</div>

<!-- Centered Pagination -->
<div class="centered-pagination text-left">
    <ul>
        {% if current_page.has_previous %}
            <li><a onclick="reloadajax('{{current_page.previous_page_number}}')" href="#">&laquo;</a></li>
        {% endif %}
        {% for i in paginator.page_range %}
            <li><a {% if i == number %}class="active"{% endif%} onclick="reloadajax('{{i}}')" href="#">{{i}}</a></li>
        {% endfor %}
        {% if current_page.has_next %}
            <li><a onclick="reloadajax('{{current_page.next_page_number}}')" href="#">&raquo;</a></li>
        {% endif %}
    </ul>
</div>

templates/sort-comment.html
                    {% for review in commentanimes %}
							<div class="media p15">
								<a class="pull-left" href="{% url 'users' username=review.user.user.username %}">
									{% if review.user.m_picture %}
										<img class="media-object avatar avatar-sm" src="{{ MEDIA_URL }}{{review.user.m_picture}}" alt="">
									{% else %}
										<img class="media-object avatar avatar-sm" src="{{ MEDIA_URL }}MembersPicture/pic.png" alt="">
									{% endif %}
								</a>
								
								<div class="comment">
									<div class="comment-author h6 no-m">
										<a href="{% url 'users' username=review.user.user.username %}"><b>{{review.user.user.username}}</b></a>
									</div>
									<div class="comment-meta small">{{review.added}}</div>
									<p>
										{{review.comment}}
									</p>

									<p class="small">
										<a id="heart-{{review.id}}" class="mr10"><i class="fa fa-heart-o mr5"></i><span id="like-{{review.id}}">{{review.votes.count}} </span> Likes</a>										
										<!--a href="#" id="heart-{{review.id}}" class="mr10 text-danger"-->
									</p>
									<script>
											
												$.get("{% url 'show_likes' entity='anime' id=review.id %}", function(data, status){						
													
													if (data.voted){
														$('#heart-{{review.id}}').addClass('text-danger');											
													}
												});
											
										</script>
									<hr>
								 </div>
							</div>
                        {% endfor %}